name: Daily cleanup

on:
  workflow_dispatch:  
  schedule:
    - cron: '0 2 * * *' # every night at 2 am UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Daily Artifact Cleanup
        uses: jimschubert/delete-artifacts-action@v1
        with:
          log_level: 'error'
          min_bytes: '0'
