name: 'nightly artifacts cleanup'
on:
  schedule:
    - cron: '57 4 * * *' # every night at 4 am UTC

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 1days # Setting this to 0 will delete all artifacts
